esphome:
  name: smartdesk

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "13ZDhPLieXiql9M9cb1OV5AVH1o/0cu6YT36CawwtDE="

ota:
  password: "7b62f23aaed65973d6a9e569a67f19da"

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smartdesk Fallback Hotspot"
    password: "Zj5Aqfxd9aTb"

captive_portal:

improv_serial:

web_server:
  port: 80

external_components:
- source: github://logiraptor/desk-controller
  refresh: 1min

standing_desk:
  id: desk
  uart_id: standing_desk_uart

uart:
  id: standing_desk_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

binary_sensor:
  - platform: template
    name: "Desk Awake"
    lambda: return id(desk).is_awake();

# Example configuration entry
sensor:
  - platform: template
    name: "Desk Height"
    lambda: return id(desk).get_desk_height();
    update_interval: 1s

  - platform: template
    name: "Desk Target Height"
    lambda: return id(desk).get_desk_target_height();
    update_interval: 1s
  
  - platform: template
    name: "Desk Standing"
    lambda: return id(desk).get_desk_height() > 30;
    update_interval: 1s

button:
  - platform: template
    name: "Desk Preset 1"
    icon: "mdi:numeric-1-box"
    on_press:
      - lambda: return id(desk).set_button_state(0x80);
      - delay: 98ms
      - lambda: return id(desk).set_button_state(0x04);
      - delay: 1s
      - lambda: return id(desk).set_button_state(0x00);
      - delay: 5s

  - platform: template
    name: "Desk Preset 2"
    icon: "mdi:numeric-2-box"
    on_press:
      - lambda: return id(desk).set_button_state(0x80);
      - delay: 98ms
      - lambda: return id(desk).set_button_state(0x08);
      - delay: 1s
      - lambda: return id(desk).set_button_state(0x00);
      - delay: 5s

  - platform: template
    name: "Desk Preset 3"
    icon: "mdi:numeric-3-box"
    on_press:
      - lambda: return id(desk).set_button_state(0x80);
      - delay: 98ms
      - lambda: return id(desk).set_button_state(0x10);
      - delay: 1s
      - lambda: return id(desk).set_button_state(0x00);
      - delay: 5s

  - platform: template
    name: "Desk Preset 4"
    icon: "mdi:numeric-4-box"
    on_press:
      - lambda: return id(desk).set_button_state(0x80);
      - delay: 98ms
      - lambda: return id(desk).set_button_state(0x20);
      - delay: 1s
      - lambda: return id(desk).set_button_state(0x00);
      - delay: 5s
